# Generated by Django 2.2.2 on 2019-06-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='title',
            field=models.CharField(db_column='name', max_length=20),
        ),
    ]
