# Generated by Django 2.2.2 on 2019-06-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_auto_20190610_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='content',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
