# Generated by Django 2.2.2 on 2019-06-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_auto_20190610_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
