# Generated by Django 2.2.2 on 2019-06-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationtest', '0003_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='addr',
            field=models.CharField(default='dongsanjie', max_length=30),
        ),
    ]
