# Generated by Django 2.2.2 on 2019-06-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationtest', '0004_temp_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='age',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
