# Generated by Django 2.2.2 on 2019-06-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationtest', '0007_auto_20190610_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='addr',
            field=models.CharField(db_column='address', default='dongsanjie', max_length=30),
        ),
    ]
