# Generated by Django 2.2.2 on 2019-06-10 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationtest', '0008_auto_20190610_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='addr',
            field=models.CharField(db_column='address', default='dongsanjie', max_length=30, verbose_name='地址'),
        ),
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationtest.AreaInfo')),
            ],
        ),
    ]
